### ISSUE TITLE
Feature: User > Account Creation

### ISSUE THREAD

**Issue by luciademoja** [CraftAcademy/slow_food_june#6]
As a user 
to be able to place an order
I need to be able to create an account

**Comment by lollypop27** [comment]
Feature: As a user
In order to get tasty food to where I am
I need to register to place an order

Scenario: allows user to register
Given I am on the "registration page"
And I enter personal information
Then I should click the register button

**Comment by rdcsg** [comment]
**Feature:** As a user
In order to get tasty food to where I am
I need to register to gain the ability to place an order

**Scenario:** Allows user to register
_Given_ I am on the "registration page"
_And_ I enter some personal information (full name, email, telephone, preferred delivery adress) into a form and click the "Register" button
_Then_ I should be registered and looking at the main page inside the service/system

**Comment by rdcsg** [comment]
**Feature:** As a user
In order to get tasty food I like to where I am
I need to register to gain the ability to place an order

**Scenario:** Allows user to register
_Given_ I am on the "registration page"
_And_ I enter some personal information (full name, email, telephone, preferred delivery adress) into a form and click the "Register" button
_Then_ I should be registered and looking at the main page inside the service/system

**Comment by rdcsg** [comment]
**Feature:** As a user
In order to get tasty food that I like to the place where I am
I need to register to gain the ability to select and buy the food I like and get it delivered

**Scenario:** Allows a user to register
_Given_ I am on the "registration page"
_And_ I enter some personal information (full name, email, telephone, preferred delivery adress) into a form and click the "Register" button
_Then_ I should be registered and looking at the main page inside the service/system

**Comment by MikaelFeher** [comment]
Doesn't `account creation` make more sense than `user registration`, so that we use links and 
buttons that refer to `create account` rather than `register`?
